### ISSUE TITLE
occasional connection failure

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/HangoutConnection#18]
Sometimes the WSO connect fails to get back to WSO ... here's an error from the console ...

```
ifr?url=app%3A%2F%2F135304697558%2Fhangout&container=hangout&view=default&lang=all&country=ALL&debu…:1458 Uncaught TypeError: Cannot read property 'callbackUrl' of null
```

I note that it worked just before and that this failure was resistant to restarts of hangout, of reloading AV etc.

**Comment by alejandrobabio** [comment]
@tansaku I did some experiments (on my heroku wso) and I think I found the cause of that.

The `event_instance_id` is building with `"#{user.id}#{project_id}#{Time.now.to_i}"` at `EventInstancesHelper#generate_event_instance_id` and it is send to the project show page in order to build the hangout button. If you use this button for first time, this works fine, the hangout session sends a message to WSO and a new EventInstance object is stored at the db. If this hangout is finished, this state keep stored at `hoa_status` field. And is forbidden update this EventInstance after finished ([code](https://github.com/AgileVentures/WebsiteOne/blob/develop/app/models/event_instance.rb#L44)), otherwise we will lost some hangouts sessions, because with the update from hangout the `yt_video_id` is updated too.

I think it could be fixed removing the `Time.now.to_i` from `event_instance_id` at WSO, and adding it at the initialize process of the hangout session at HangoutConnection. After that, each hangout sesion started will have it's own "Time", and it will not overlap other HangoutEvent. 

Just let me know what you think about this, and I will try to make the change on the next days.

**Comment by tansaku** [comment]
@alejandrobabio thanks - very interesting - sorry hadn't reviewed yet - will do so tomorrow

**Comment by tansaku** [comment]
@alejandrobabio I've had a closer look at this and I can't say that I'm following it exactly :-)

I don't think I could validate what you are saying without spending more time on it.  I could do that, but I'm about to go on break.  I'd say try to wrap the issue as you see it in a test, and get that in a PR, and then follow up with a fix if you think you've got one.

@diraulo can review and/or I'll take a more detailed look when I'm back in 10 days, but a PR would be very welcome

Thanks so much for your ongoing efforts!
